"""Curated RDKit-validated example molecule library for the Streamlit app."""

from __future__ import annotations

EXAMPLE_CATEGORIES = (
    'Analgesics/NSAIDs',
    'PK teaching examples',
    'CNS drugs',
    'Cardiovascular drugs',
    'Antibiotics',
    'Antivirals',
    'Oncology drugs',
    'Steroids/hormones',
    'GI drugs',
    'Immunosuppressants',
    'Natural products/cannabinoids',
    'Highly polar/low permeability examples',
    'Lipophilic/high permeability examples',
)

EXAMPLE_MOLECULES = (
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Aspirin',
        "smiles": 'CC(=O)Oc1ccccc1C(=O)O',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Ibuprofen',
        "smiles": 'CC(C)Cc1ccc(C(C)C(=O)O)cc1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Acetaminophen',
        "smiles": 'CC(=O)Nc1ccc(O)cc1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Naproxen',
        "smiles": 'COc1ccc2cc(C(C)C(=O)O)ccc2c1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Diclofenac',
        "smiles": 'O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Ketoprofen',
        "smiles": 'CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Indomethacin',
        "smiles": 'COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Celecoxib',
        "smiles": 'Cc1ccc(-c2cc(C(F)(F)F)nn2-c2ccc(S(N)(=O)=O)cc2)cc1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Meloxicam',
        "smiles": 'Cc1cnc(NC(=O)C2=C(O)c3ccccc3S(=O)(=O)N2C)s1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Piroxicam',
        "smiles": 'CN1C(C(=O)Nc2ccccn2)=C(O)c2ccccc2S1(=O)=O',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Etodolac',
        "smiles": 'CCc1cccc2c3c([nH]c12)C(CC)(CC(=O)O)OCC3',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Sulindac',
        "smiles": 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Ketorolac',
        "smiles": 'O=C(c1ccccc1)c1ccc2n1CCC2C(=O)O',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Mefenamic acid',
        "smiles": 'Cc1cccc(Nc2ccccc2C(=O)O)c1C',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Morphine',
        "smiles": 'CN1CCC23c4c5ccc(O)c4OC2C(O)C=CC3C1C5',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Codeine',
        "smiles": 'COc1ccc2c3c1OC1C(O)C=CC4C(C2)N(C)CCC341',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Tramadol',
        "smiles": 'COc1cccc(C2(O)CCCCC2CN(C)C)c1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Oxycodone',
        "smiles": 'COc1ccc2c3c1OC1C(=O)CCC4(O)C(C2)N(C)CCC314',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'Analgesics/NSAIDs',
        "name": 'Fentanyl',
        "smiles": 'CCC(=O)N(c1ccccc1)C1CCN(CCc2ccccc2)CC1',
        "teaching_note": 'Analgesic/NSAID example for comparing acidity, lipophilicity, and permeability-related descriptors.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Lidocaine',
        "smiles": 'CCN(CC)CC(=O)Nc1c(C)cccc1C',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Bupivacaine',
        "smiles": 'CCCCN1CCCCC1C(=O)Nc1c(C)cccc1C',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Diazepam',
        "smiles": 'CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc21',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Midazolam',
        "smiles": 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Alprazolam',
        "smiles": 'Cc1nnc2n1-c1ccc(Cl)cc1C(c1ccccc1)=NC2',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Lorazepam',
        "smiles": 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2Cl)=NC1O',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Clonazepam',
        "smiles": 'O=C1CN=C(c2ccccc2Cl)c2cc([N+](=O)[O-])ccc2N1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Fluoxetine',
        "smiles": 'CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Sertraline',
        "smiles": 'CNC1CCC(c2ccc(Cl)c(Cl)c2)c2ccccc21',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Paroxetine',
        "smiles": 'Fc1ccc(C2CCNCC2COc2ccc3c(c2)OCO3)cc1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Citalopram',
        "smiles": 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Escitalopram',
        "smiles": 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Venlafaxine',
        "smiles": 'COc1ccc(C(CN(C)C)C2(O)CCCCC2)cc1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Duloxetine',
        "smiles": 'CNCCC(Oc1cccc2ccccc12)c1cccs1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Clozapine',
        "smiles": 'CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Haloperidol',
        "smiles": 'O=C(CCCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Risperidone',
        "smiles": 'Cc1nc2n(c(=O)c1CCN1CCC(c3noc4cc(F)ccc34)CC1)CCCC2',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Quetiapine',
        "smiles": 'OCCOCCN1CCN(C2=Nc3ccccc3Sc3ccccc32)CC1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Olanzapine',
        "smiles": 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Carbamazepine',
        "smiles": 'NC(=O)N1c2ccccc2C=Cc2ccccc21',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Phenytoin',
        "smiles": 'O=C1NC(=O)C(c2ccccc2)(c2ccccc2)N1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Valproic acid',
        "smiles": 'CCCC(CCC)C(=O)O',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Lamotrigine',
        "smiles": 'Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Levetiracetam',
        "smiles": 'CCC(C(N)=O)N1CCCC1=O',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Gabapentin',
        "smiles": 'NCC1(CC(=O)O)CCCCC1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Pregabalin',
        "smiles": 'CC(C)CC(CN)CC(=O)O',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Ketamine',
        "smiles": 'CNC1(c2ccccc2Cl)CCCCC1=O',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Propofol',
        "smiles": 'CC(C)c1cccc(C(C)C)c1O',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Zolpidem',
        "smiles": 'Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Bupropion',
        "smiles": 'CC(NC(C)(C)C)C(=O)c1cccc(Cl)c1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'CNS drugs',
        "name": 'Methylphenidate',
        "smiles": 'COC(=O)C(c1ccccc1)C1CCCCN1',
        "teaching_note": 'CNS-active example useful for discussing lipophilicity, polarity, and blood-brain exposure hypotheses.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Warfarin',
        "smiles": 'CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Propranolol',
        "smiles": 'CC(C)NCC(O)COc1cccc2ccccc12',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Metoprolol',
        "smiles": 'COCCc1ccc(OCC(O)CNC(C)C)cc1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Atenolol',
        "smiles": 'CC(C)NCC(O)COc1ccc(CC(N)=O)cc1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Verapamil',
        "smiles": 'COc1ccc(CCN(C)CCCC(C#N)(c2ccc(OC)c(OC)c2)C(C)C)cc1OC',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Diltiazem',
        "smiles": 'COc1ccc(C2Sc3ccccc3N(CCN(C)C)C(=O)C2OC(C)=O)cc1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Amlodipine',
        "smiles": 'CCOC(=O)C1=C(COCCN)NC(C)=C(C(=O)OC)C1c1ccccc1Cl',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Losartan',
        "smiles": 'CCCCc1nc(Cl)c(CO)n1Cc1ccc(-c2ccccc2-c2nn[nH]n2)cc1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Valsartan',
        "smiles": 'CCCCC(=O)N(Cc1ccc(-c2ccccc2-c2nn[nH]n2)cc1)C(C(=O)O)C(C)C',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Lisinopril',
        "smiles": 'NCCCCC(NC(CCc1ccccc1)C(=O)O)C(=O)N1CCCC1C(=O)O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Enalapril',
        "smiles": 'CCOC(=O)C(CCc1ccccc1)NC(C)C(=O)N1CCCC1C(=O)O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Captopril',
        "smiles": 'CC(CS)C(=O)N1CCCC1C(=O)O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Furosemide',
        "smiles": 'NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Hydrochlorothiazide',
        "smiles": 'NS(=O)(=O)c1cc2c(cc1Cl)NCNS2(=O)=O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Spironolactone',
        "smiles": 'CC(=O)SC1CC2=CC(=O)CCC2(C)C2CCC3(C)C(CCC34CCC(=O)O4)C12',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Digoxin',
        "smiles": 'CC1OC(OC2C(O)CC(OC3C(O)CC(OC4CCC5(C)C(CCC6C5CC(O)C5(C)C(C7=CC(=O)OC7)CCC65O)C4)OC3C)OC2C)CC(O)C1O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Atorvastatin',
        "smiles": 'CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)n1CCC(O)CC(O)CC(=O)O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Simvastatin',
        "smiles": 'CCC(C)(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O)O3)C21',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Rosuvastatin',
        "smiles": 'CC(C)c1nc(N(C)S(C)(=O)=O)nc(-c2ccc(F)cc2)c1C=CC(O)CC(O)CC(=O)O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Pravastatin',
        "smiles": 'CCC(C)C(=O)OC1CC(O)C=C2C=CC(C)C(CCC(O)CC(O)CC(=O)O)C21',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Apixaban',
        "smiles": 'COc1ccc(-n2nc(C(N)=O)c3c2C(=O)N(c2ccc(N4CCCCC4=O)cc2)CC3)cc1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Rivaroxaban',
        "smiles": 'O=C(NCC1CN(c2ccc(N3CCOCC3=O)cc2)C(=O)O1)c1ccc(Cl)s1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Clopidogrel',
        "smiles": 'COC(=O)C(c1ccccc1Cl)N1CCc2sccc2C1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Ticagrelor',
        "smiles": 'CCCSc1nc(NC2CC2c2ccc(F)c(F)c2)c2nnn(C3CC(OCCO)C(O)C3O)c2n1',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Sildenafil',
        "smiles": 'CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Cardiovascular drugs',
        "name": 'Tadalafil',
        "smiles": 'CN1CC(=O)N2C(Cc3c([nH]c4ccccc34)C2c2ccc3c(c2)OCO3)C1=O',
        "teaching_note": 'Cardiovascular example for comparing polarity, ionization, size, and permeability risk.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Ciprofloxacin',
        "smiles": 'O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Levofloxacin',
        "smiles": 'CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Moxifloxacin',
        "smiles": 'COc1c(N2CC3CCCNC3C2)c(F)cc2c(=O)c(C(=O)O)cn(C3CC3)c12',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Azithromycin',
        "smiles": 'CCC1OC(=O)C(C)C(OC2CC(C)(OC)C(O)C(C)O2)C(C)C(OC2OC(C)CC(N(C)C)C2O)C(C)(O)CC(C)CN(C)C(C)C(O)C1(C)O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Erythromycin',
        "smiles": 'CCC1OC(=O)C(C)C(OC2CC(C)(OC)C(O)C(C)O2)C(C)C(OC2OC(C)CC(N(C)C)C2O)C(C)(O)CC(C)C(=O)C(C)C(O)C1(C)O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Clarithromycin',
        "smiles": 'CCC1OC(=O)C(C)C(OC2CC(C)(OC)C(O)C(C)O2)C(C)C(OC2OC(C)CC(N(C)C)C2O)C(C)(OC)CC(C)C(=O)C(C)C(O)C1(C)O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Amoxicillin',
        "smiles": 'CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=O)O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Penicillin G',
        "smiles": 'CC1(C)SC2C(NC(=O)Cc3ccccc3)C(=O)N2C1C(=O)O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Ceftriaxone',
        "smiles": 'CON=C(C(=O)NC1C(=O)N2C(C(=O)O)=C(CSc3nc(=O)c(=O)[nH]n3C)CSC12)c1csc(N)n1',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Cephalexin',
        "smiles": 'CC1=C(C(=O)O)N2C(=O)C(NC(=O)C(N)c3ccccc3)C2SC1',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Doxycycline',
        "smiles": 'CC1c2cccc(O)c2C(O)=C2C(=O)C3(O)C(O)=C(C(N)=O)C(=O)C(N(C)C)C3C(O)C21',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Tetracycline',
        "smiles": 'CN(C)C1C(=O)C(C(N)=O)=C(O)C2(O)C(=O)C3=C(O)c4c(O)cccc4C(C)(O)C3CC12',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Vancomycin',
        "smiles": 'CNC(CC(C)C)C(=O)NC1C(=O)NC(CC(N)=O)C(=O)NC2C(=O)NC3C(=O)NC(C(=O)NC(C(=O)O)c4cc(O)cc(O)c4-c4cc3ccc4O)C(O)c3ccc(c(Cl)c3)Oc3cc2cc(c3OC2OC(CO)C(O)C(O)C2OC2CC(C)(N)C(O)C(C)O2)Oc2ccc(cc2Cl)C1O',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Rifampin',
        "smiles": 'COC1C=COC2(C)Oc3c(C)c(O)c4c(O)c(c(C=NN5CCN(C)CC5)c(O)c4c3C2=O)NC(=O)C(C)=CC=CC(C)C(O)C(C)C(O)C(C)C(OC(C)=O)C1C',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Isoniazid',
        "smiles": 'NNC(=O)c1ccncc1',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Linezolid',
        "smiles": 'CC(=O)NCC1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Metronidazole',
        "smiles": 'Cc1ncc([N+](=O)[O-])n1CCO',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Trimethoprim',
        "smiles": 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antibiotics',
        "name": 'Sulfamethoxazole',
        "smiles": 'Cc1cc(NS(=O)(=O)c2ccc(N)cc2)no1',
        "teaching_note": 'Antibiotic example showing why high polarity or size can complicate passive permeability interpretation.',
    },
    {
        "category": 'Antivirals',
        "name": 'Remdesivir',
        "smiles": 'CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N)ncnn23)C(O)C1O)Oc1ccccc1',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Ritonavir',
        "smiles": 'CC(C)c1nc(CN(C)C(=O)NC(C(=O)NC(Cc2ccccc2)CC(O)C(Cc2ccccc2)NC(=O)OCc2cncs2)C(C)C)cs1',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Lopinavir',
        "smiles": 'Cc1cccc(C)c1OCC(=O)NC(Cc1ccccc1)C(O)CC(Cc1ccccc1)NC(=O)C(C(C)C)N1CCCNC1=O',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Acyclovir',
        "smiles": 'Nc1nc2c(ncn2COCCO)c(=O)[nH]1',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Valacyclovir',
        "smiles": 'CC(C)C(N)C(=O)OCCOCn1cnc2c(=O)[nH]c(N)nc21',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Oseltamivir',
        "smiles": 'CCOC(=O)C1=CC(OC(CC)CC)C(NC(C)=O)C(N)C1',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Molnupiravir',
        "smiles": 'CC(C)C(=O)OCC1OC(n2ccc(NO)nc2=O)C(O)C1O',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Tenofovir',
        "smiles": 'CC(Cn1cnc2c(N)ncnc21)OCP(=O)(O)O',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Zidovudine',
        "smiles": 'Cc1cn(C2CC(N=[N+]=[N-])C(CO)O2)c(=O)[nH]c1=O',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Lamivudine',
        "smiles": 'Nc1ccn(C2CSC(CO)O2)c(=O)n1',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Antivirals',
        "name": 'Efavirenz',
        "smiles": 'O=C1Nc2ccc(Cl)cc2C(C#CC2CC2)(C(F)(F)F)O1',
        "teaching_note": 'Antiviral example useful for discussing prodrugs, polarity, and model-domain caution.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Doxorubicin',
        "smiles": 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3OC1CC(N)C(O)C(C)O1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Paclitaxel',
        "smiles": 'CC(=O)OC1C(=O)C2(C)C(O)CC3OCC3(OC(C)=O)C2C(OC(=O)c2ccccc2)C2(O)CC(OC(=O)C(O)C(NC(=O)c3ccccc3)c3ccccc3)C(C)=C1C2(C)C',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Imatinib',
        "smiles": 'Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc(-c2cccnc2)n1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Erlotinib',
        "smiles": 'C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Gefitinib',
        "smiles": 'COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Tamoxifen',
        "smiles": 'CCC(=C(c1ccccc1)c1ccc(OCCN(C)C)cc1)c1ccccc1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Methotrexate',
        "smiles": 'CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)O)C(=O)O)cc1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": '5-Fluorouracil',
        "smiles": 'O=c1[nH]cc(F)c(=O)[nH]1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Cyclophosphamide',
        "smiles": 'O=P1(N(CCCl)CCCl)NCCCO1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Cisplatin',
        "smiles": 'N.N.[Cl][Pt][Cl]',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Carboplatin',
        "smiles": 'N.N.O=C([O-])C1(C(=O)[O-])CCC1.[Pt+2]',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Etoposide',
        "smiles": 'COc1cc(C2c3cc4c(cc3C(OC3OC5COC(C)OC5C(O)C3O)C3COC(=O)C23)OCO4)cc(OC)c1O',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Vincristine',
        "smiles": 'CCC1(O)CC2CN(CCc3c([nH]c4ccccc34)C(C(=O)OC)(c3cc4c(cc3OC)N(C=O)C3C(O)(C(=O)OC)C(OC(C)=O)C5(CC)C=CCN6CCC43C65)C2)C1',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Bortezomib',
        "smiles": 'CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B(O)O',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Oncology drugs',
        "name": 'Capecitabine',
        "smiles": 'CCCCCOC(=O)Nc1nc(=O)n(C2OC(C)C(O)C2O)cc1F',
        "teaching_note": 'Oncology example often outside simple drug-like space; review applicability-domain output carefully.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Dexamethasone',
        "smiles": 'CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)CO',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Prednisone',
        "smiles": 'CC12C=CC(=O)C=C1CCC1C2C(=O)CC2(C)C1CCC2(O)C(=O)CO',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Cortisol',
        "smiles": 'CC12CCC(=O)C=C1CCC1C2C(O)CC2(C)C1CCC2(O)C(=O)CO',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Testosterone',
        "smiles": 'CC12CCC(=O)C=C1CCC1C2CCC2(C)C(O)CCC12',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Estradiol',
        "smiles": 'CC12CCC3c4ccc(O)cc4CCC3C1CCC2O',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Progesterone',
        "smiles": 'CC(=O)C1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Levothyroxine',
        "smiles": 'NC(Cc1cc(I)c(Oc2cc(I)c(O)c(I)c2)c(I)c1)C(=O)O',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Liothyronine',
        "smiles": 'NC(Cc1cc(I)c(Oc2ccc(O)c(I)c2)c(I)c1)C(=O)O',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Melatonin',
        "smiles": 'COc1ccc2[nH]cc(CCNC(C)=O)c2c1',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Vitamin D3',
        "smiles": 'C=C1CCC(O)CC1=CC=C1CCCC2(C)C1CCC2C(C)CCCC(C)C',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'Steroids/hormones',
        "name": 'Retinoic acid',
        "smiles": 'CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CC(=O)O',
        "teaching_note": 'Steroid or hormone example for comparing lipophilic scaffolds and permeability-friendly descriptors.',
    },
    {
        "category": 'GI drugs',
        "name": 'Omeprazole',
        "smiles": 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Pantoprazole',
        "smiles": 'COc1ccnc(CS(=O)c2nc3ccc(OC(F)F)cc3[nH]2)c1OC',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Esomeprazole',
        "smiles": 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Lansoprazole',
        "smiles": 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccccc2[nH]1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Famotidine',
        "smiles": 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Ranitidine',
        "smiles": 'CNC(=C[N+](=O)[O-])NCCSCc1ccc(CN(C)C)o1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Ondansetron',
        "smiles": 'Cc1nccn1CC1CCc2c(c3ccccc3n2C)C1=O',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Metoclopramide',
        "smiles": 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Loperamide',
        "smiles": 'CN(C)C(=O)C(CCN1CCC(O)(c2ccc(Cl)cc2)CC1)(c1ccccc1)c1ccccc1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'GI drugs',
        "name": 'Mesalamine',
        "smiles": 'Nc1ccc(O)c(C(=O)O)c1',
        "teaching_note": 'GI pharmacology example for reviewing acid suppression, antiemetic, and gut-exposure chemistry.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Cyclosporine',
        "smiles": 'CC=CCC(C)C(O)C1C(=O)NC(CC)C(=O)N(C)CC(=O)N(C)C(CC(C)C)C(=O)NC(C(C)C)C(=O)N(C)C(CC(C)C)C(=O)NC(C)C(=O)NC(C)C(=O)N(C)C(CC(C)C)C(=O)N(C)C(CC(C)C)C(=O)N(C)C(C(C)C)C(=O)N1C',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Tacrolimus',
        "smiles": 'C=CCC1C=C(C)CC(C)CC(OC)C2OC(O)(C(=O)C(=O)N3CCCCC3C(=O)OC(C(C)=CC3CCC(O)C(OC)C3)C(C)C(O)CC1=O)C(C)CC2OC',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Sirolimus',
        "smiles": 'COC1CC2CCC(C)C(O)(O2)C(=O)C(=O)N2CCCCC2C(=O)OC(C(C)CC2CCC(O)C(OC)C2)CC(=O)C(C)C=C(C)C(O)C(OC)C(=O)C(C)CC(C)C=CC=CC=C1C',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Mycophenolic acid',
        "smiles": 'COc1c(C)c2c(c(O)c1CC=C(C)CCC(=O)O)C(=O)OC2',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Azathioprine',
        "smiles": 'Cn1cnc([N+](=O)[O-])c1Sc1ncnc2nc[nH]c12',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Colchicine',
        "smiles": 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1C(NC(C)=O)CC2',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Allopurinol',
        "smiles": 'O=c1[nH]cnc2[nH]ncc12',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Immunosuppressants',
        "name": 'Folic acid',
        "smiles": 'Nc1nc2ncc(CNc3ccc(C(=O)NC(CCC(=O)O)C(=O)O)cc3)nc2c(=O)[nH]1',
        "teaching_note": 'Immunosuppressant example; larger structures can challenge descriptor-only permeability expectations.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Nicotine',
        "smiles": 'CN1CCCC1c1cccnc1',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'THC',
        "smiles": 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)=CC21',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Cannabidiol',
        "smiles": 'C=C(C)C1CCC(C)=CC1c1c(O)cc(CCCCC)cc1O',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Theophylline',
        "smiles": 'Cn1c(=O)c2[nH]cnc2n(C)c1=O',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Atropine',
        "smiles": 'CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Quinine',
        "smiles": 'C=CC1CN2CCC1CC2C(O)c1ccnc2ccc(OC)cc12',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Chloroquine',
        "smiles": 'CCN(CC)CCCC(C)Nc1ccnc2cc(Cl)ccc12',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'Natural products/cannabinoids',
        "name": 'Hydroxychloroquine',
        "smiles": 'CCN(CCO)CCCC(C)Nc1ccnc2cc(Cl)ccc12',
        "teaching_note": 'Natural product or cannabinoid example for contrasting lipophilic and alkaloid-like chemistry.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Ethanol',
        "smiles": 'CCO',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Phenacetin',
        "smiles": 'CCOc1ccc(NC(C)=O)cc1',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Antipyrine',
        "smiles": 'Cc1cc(=O)n(-c2ccccc2)n1C',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Metformin',
        "smiles": 'CN(C)C(=N)N=C(N)N',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Creatinine',
        "smiles": 'CN1CC(=O)N=C1N',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Mannitol',
        "smiles": 'OCC(O)C(O)C(O)C(O)CO',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'PK teaching examples',
        "name": 'Thiopental',
        "smiles": 'CCCC(C)C1(CC)C(=O)NC(=S)NC1=O',
        "teaching_note": 'Teaching compound for connecting molecular descriptors with PK/NCA concepts without clinical claims.',
    },
    {
        "category": 'Highly polar/low permeability examples',
        "name": 'Glucose',
        "smiles": 'OCC1OC(O)C(O)C(O)C1O',
        "teaching_note": 'Highly polar example expected to challenge passive permeability.',
    },
    {
        "category": 'Highly polar/low permeability examples',
        "name": 'Glycine',
        "smiles": 'NCC(=O)O',
        "teaching_note": 'Highly polar example expected to challenge passive permeability.',
    },
    {
        "category": 'Highly polar/low permeability examples',
        "name": 'Urea',
        "smiles": 'NC(N)=O',
        "teaching_note": 'Highly polar example expected to challenge passive permeability.',
    },
    {
        "category": 'Highly polar/low permeability examples',
        "name": 'Dopamine',
        "smiles": 'NCCc1ccc(O)c(O)c1',
        "teaching_note": 'Highly polar example expected to challenge passive permeability.',
    },
    {
        "category": 'Lipophilic/high permeability examples',
        "name": 'Biphenyl',
        "smiles": 'c1ccc(-c2ccccc2)cc1',
        "teaching_note": 'Lipophilic example for discussing permeability-solubility tradeoffs.',
    },
    {
        "category": 'Lipophilic/high permeability examples',
        "name": 'Naphthalene',
        "smiles": 'c1ccc2ccccc2c1',
        "teaching_note": 'Lipophilic example for discussing permeability-solubility tradeoffs.',
    },
    {
        "category": 'Lipophilic/high permeability examples',
        "name": 'Toluene',
        "smiles": 'Cc1ccccc1',
        "teaching_note": 'Lipophilic example for discussing permeability-solubility tradeoffs.',
    },
)

EXAMPLE_MOLECULE_COUNT = len(EXAMPLE_MOLECULES)
